"""initial migration

Revision ID: aa79b1808989
Revises: 769666e232d0
Create Date: 2021-02-28 15:24:10.574216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa79b1808989'
down_revision = '769666e232d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=64), nullable=True))
    # ### end Alembic commands ###
