"""addproxy

Revision ID: bfa36443676b
Revises: f307f25ddcce
Create Date: 2022-02-08 18:17:15.134858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfa36443676b'
down_revision = 'f307f25ddcce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxyservers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ipv4', sa.String(length=64), nullable=True),
    sa.Column('ipv6', sa.String(length=64), nullable=True),
    sa.Column('isipv6', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('servers', sa.Column('ssurl', sa.String(length=128), nullable=True))
    op.add_column('servers', sa.Column('v2rayurl', sa.String(length=128), nullable=True))
    op.drop_column('servers', 'password')
    op.drop_column('servers', 'remark')
    op.drop_column('servers', 'linknode')
    op.drop_column('servers', 'name')
    op.drop_column('servers', 'method')
    op.drop_column('servers', 'port')
    op.drop_column('servers', 'host')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('servers', sa.Column('host', sa.VARCHAR(length=64), nullable=True))
    op.add_column('servers', sa.Column('port', sa.VARCHAR(length=64), nullable=True))
    op.add_column('servers', sa.Column('method', sa.VARCHAR(length=64), nullable=True))
    op.add_column('servers', sa.Column('name', sa.VARCHAR(length=32), nullable=True))
    op.add_column('servers', sa.Column('linknode', sa.VARCHAR(length=64), nullable=True))
    op.add_column('servers', sa.Column('remark', sa.VARCHAR(length=64), nullable=True))
    op.add_column('servers', sa.Column('password', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('servers', 'v2rayurl')
    op.drop_column('servers', 'ssurl')
    op.drop_table('proxyservers')
    # ### end Alembic commands ###
